# define some colors (R, G, B)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARKGREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
BLUE = (66, 134, 244)
BROWN = (147, 96, 59)
DARK_BLUE = (58, 112, 150)
# game settings

FPS: int = 60
TITLE = "Tilemap Demo"
BGCOLOR = DARKGREY

# Display settings
TILE_SIZE = 28

WIDTH = int(TILE_SIZE * 48)
HEIGHT = int(TILE_SIZE * 28)

# MENU SETTINGS
MENU_WIDTH = int(TILE_SIZE * 6)
MENU_START_X = int(WIDTH - MENU_WIDTH)

# MENU MODE BUTTONS
MODE_BUTTON_SIZE = TILE_SIZE
DEFENCE_MODE_X = MENU_START_X
ATTACK_MODE_X = DEFENCE_MODE_X + MODE_BUTTON_SIZE
MODE_Y = 0

# MENU IMAGE
MENU_IMAGE_HEIGHT = TILE_SIZE * 5
MENU_IMAGE_WIDTH = TILE_SIZE * 6
MENU_IMAGE_Y = MODE_BUTTON_SIZE
MENU_IMAGE_X = MENU_START_X

# MENU DATA LIST
DATA_LIST_WIDTH = MENU_WIDTH
DATA_LIST_HEIGHT = HEIGHT - (MODE_BUTTON_SIZE + MENU_IMAGE_HEIGHT)
DATA_LIST_X = WIDTH - MENU_WIDTH
DATA_LIST_Y = MODE_BUTTON_SIZE + MENU_IMAGE_HEIGHT
DATA_RECORD_WIDTH = DATA_LIST_WIDTH
DATA_RECORD_HEIGHT = TILE_SIZE * 3

# ARENA
ARENA_WIDTH = WIDTH - MENU_WIDTH
ARENA_HEIGHT = HEIGHT

ARENA_TILE_WIDTH = int(ARENA_WIDTH / TILE_SIZE)
ARENA_TILE_HEIGHT = int(ARENA_HEIGHT / TILE_SIZE)