# define some colors (R, G, B)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
DARK_GREY = (40, 40, 40)
LIGHTGREY = (100, 100, 100)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
YELLOW = (255, 255, 0)
BLUE = (66, 134, 244)
BROWN = (147, 96, 59)
DARK_BLUE = (58, 112, 150)
DARK_GREEN = (38, 77, 0)
# game settings

FPS: int = 60
TITLE = "Tower Wars"
BGCOLOR = DARK_GREEN

# Display settings
TILE_SIZE = 32

WIDTH = int(TILE_SIZE * 42)
HEIGHT = int(TILE_SIZE * 28)

# MENU SETTINGS
MENU_WIDTH = int(TILE_SIZE * 6)
MENU_START_X = WIDTH - MENU_WIDTH


# MENU IMAGE
MENU_IMAGE_HEIGHT = TILE_SIZE * 5
MENU_IMAGE_WIDTH = TILE_SIZE * 6
MENU_IMAGE_Y = 0
MENU_IMAGE_X = MENU_START_X


# MENU MODE BUTTONS
MODE_BUTTON_SIZE = TILE_SIZE
DEFENCE_MODE_X = MENU_START_X
ATTACK_MODE_X = DEFENCE_MODE_X + MODE_BUTTON_SIZE
MODE_Y = MENU_IMAGE_HEIGHT


# MENU DATA LIST
DATA_LIST_WIDTH = MENU_WIDTH
DATA_LIST_HEIGHT = HEIGHT - (MODE_BUTTON_SIZE + MENU_IMAGE_HEIGHT)
DATA_LIST_X = MENU_START_X
DATA_LIST_Y = MODE_BUTTON_SIZE + MENU_IMAGE_HEIGHT
DATA_RECORD_WIDTH = DATA_LIST_WIDTH
DATA_RECORD_HEIGHT = TILE_SIZE * 3

# MENU READY BTN

MENU_READY_HEIGHT = TILE_SIZE * 2
MENU_READY_WIDTH = DATA_LIST_WIDTH
MENU_READY_X = MENU_START_X
MENU_READY_Y = HEIGHT - MENU_READY_HEIGHT


# ARENA
ARENA_WIDTH = WIDTH - MENU_WIDTH
ARENA_HEIGHT = HEIGHT

ARENA_TILE_WIDTH = int(ARENA_WIDTH / TILE_SIZE)
ARENA_TILE_HEIGHT = int(ARENA_HEIGHT / TILE_SIZE)